sudo:required
services:
    - docker

before_install:
    - docker build -t venuvayila/docker-react -f Dockerfile.dev

scripts:
    - docker run venuvayila/docker-react npm run test -- --coverage
