language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t venuvayila/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true venuvayila/docker-react npm run test
